### ISSUE TITLE
360的壳脱不了？

### ISSUE THREAD

**Issue by gqdy365** [gnaixx/dex-hdog#1]
启动之后空白界面，报错：
`05-17 02:17:36.497: A/libc(21719): Fatal signal 4 (SIGILL), code 1, fault addr 0xb6f761dc in tid 21719 (hound-e.so)
05-17 02:17:36.598: A/DEBUG(197): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-17 02:17:36.598: A/DEBUG(197): Build fingerprint: 'google/hammerhead/hammerhead:6.0.1/MOB30M/2862625:user/release-keys'
05-17 02:17:36.598: A/DEBUG(197): Revision: '11'
05-17 02:17:36.598: A/DEBUG(197): ABI: 'arm'
05-17 02:17:36.598: A/DEBUG(197): pid: 21719, tid: 21719, name: hound-e.so  >>> /data/user/0/cc.gnaixx.hdog/cache/armeabi-v7a/hound-e.so <<<
05-17 02:17:36.598: A/DEBUG(197): signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0xb6f761dc
05-17 02:17:36.599: W/NativeCrashListener(4484): Couldn't find ProcessRecord for pid 21719
05-17 02:17:36.600: A/DEBUG(197):     r0 00000026  r1 00000000  r2 00004001  r3 00000001
05-17 02:17:36.600: E/DEBUG(197): AM write failed: Broken pipe
05-17 02:17:36.600: A/DEBUG(197):     r4 00003612  r5 be8a9840  r6 56cdfd8f  r7 be8a97e8
05-17 02:17:36.600: A/DEBUG(197):     r8 00000000  r9 00000000  sl 00000000  fp be8a9a7c
05-17 02:17:36.600: A/DEBUG(197):     ip 000054d7  sp be8a8d50  lr b6f761db  pc b6f761dc  cpsr 400f0030
05-17 02:17:36.592: W/debuggerd(197): type=1400 audit(0.0:4891): avc: denied { search } for name="cc.gnaixx.hdog" dev="mmcblk0p28" ino=1499822 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
05-17 02:17:36.592: W/debuggerd(197): type=1400 audit(0.0:4892): avc: denied { search } for name="cc.gnaixx.hdog" dev="mmcblk0p28" ino=1499822 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
05-17 02:17:36.602: W/debuggerd(197): type=1400 audit(0.0:4893): avc: denied { search } for name="cc.gnaixx.hdog" dev="mmcblk0p28" ino=1499822 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
05-17 02:17:36.605: A/DEBUG(197): backtrace:
05-17 02:17:36.605: A/DEBUG(197):     #00 pc 000011dc  /data/data/cc.gnaixx.hdog/cache/armeabi-v7a/hound-e.so
05-17 02:17:36.605: A/DEBUG(197):     #01 pc 000017f1  /data/data/cc.gnaixx.hdog/cache/armeabi-v7a/hound-e.so
05-17 02:17:36.605: A/DEBUG(197):     #02 pc 00017359  /system/lib/libc.so (__libc_init+44)
05-17 02:17:36.605: A/DEBUG(197):     #03 pc 00000ba8  /data/data/cc.gnaixx.hdog/cache/armeabi-v7a/hound-e.so
05-17 02:17:36.624: A/DEBUG(197): Tombstone written to: /data/tombstones/tombstone_01
05-17 02:17:36.624: I/BootReceiver(4484): Copying /data/tombstones/tombstone_01 to DropBox (SYSTEM_TOMBSTONE)
05-17 02:17:36.905: W/PlatformStatsUtil(5337): Could not retrieve Usage & Diagnostics setting. Giving up.
05-17 02:17:37.987: A/libc(21728): Fatal signal 4 (SIGILL), code 1, fault addr 0xb6f1a1dc in tid 21728 (hound-e.so)
05-17 02:17:38.082: W/debuggerd(197): type=1400 audit(0.0:4894): avc: denied { search } for name="cc.gnaixx.hdog" dev="mmcblk0p28" ino=1499822 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
05-17 02:17:38.088: A/DEBUG(197): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-17 02:17:38.088: A/DEBUG(197): Build fingerprint: 'google/hammerhead/hammerhead:6.0.1/MOB30M/2862625:user/release-keys'
05-17 02:17:38.088: A/DEBUG(197): Revision: '11'
05-17 02:17:38.088: A/DEBUG(197): ABI: 'arm'
05-17 02:17:38.088: A/DEBUG(197): pid: 21728, tid: 21728, name: hound-e.so  >>> /data/user/0/cc.gnaixx.hdog/cache/armeabi-v7a/hound-e.so <<<
05-17 02:17:38.088: A/DEBUG(197): signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0xb6f1a1dc
05-17 02:17:38.089: W/NativeCrashListener(4484): Couldn't find ProcessRecord for pid 21728
05-17 02:17:38.089: A/DEBUG(197):     r0 00000026  r1 00000000  r2 00004001  r3 00000001
05-17 02:17:38.089: E/DEBUG(197): AM write failed: Broken pipe
05-17 02:17:38.089: A/DEBUG(197):     r4 00003612  r5 beb29840  r6 68736912  r7 beb297e8
05-17 02:17:38.089: A/DEBUG(197):     r8 00000000  r9 00000000  sl 00000000  fp beb29a7c
05-17 02:17:38.089: A/DEBUG(197):     ip 000054e0  sp beb28d50  lr b6f1a1db  pc b6f1a1dc  cpsr 400f0030
05-17 02:17:38.092: A/DEBUG(197): backtrace:
05-17 02:17:38.092: A/DEBUG(197):     #00 pc 000011dc  /data/data/cc.gnaixx.hdog/cache/armeabi-v7a/hound-e.so
05-17 02:17:38.092: A/DEBUG(197):     #01 pc 000017f1  /data/data/cc.gnaixx.hdog/cache/armeabi-v7a/hound-e.so
05-17 02:17:38.082: W/debuggerd(197): type=1400 audit(0.0:4895): avc: denied { search } for name="cc.gnaixx.hdog" dev="mmcblk0p28" ino=1499822 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
05-17 02:17:38.092: A/DEBUG(197):     #02 pc 00017359  /system/lib/libc.so (__libc_init+44)
05-17 02:17:38.092: A/DEBUG(197):     #03 pc 00000ba8  /data/data/cc.gnaixx.hdog/cache/armeabi-v7a/hound-e.so
05-17 02:17:38.092: W/debuggerd(197): type=1400 audit(0.0:4896): avc: denied { search } for name="cc.gnaixx.hdog" dev="mmcblk0p28" ino=1499822 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
05-17 02:17:38.108: A/DEBUG(197): Tombstone written to: /data/tombstones/tombstone_02
05-17 02:17:38.109: I/BootReceiver(4484): Copying /data/tombstones/tombstone_02 to DropBox (SYSTEM_TOMBSTONE)
05-17 02:17:39.460: A/libc(21736): Fatal signal 4 (SIGILL), code 1, fault addr 0xb6fc31dc in tid 21736 (hound-e.so)
05-17 02:17:39.561: A/DEBUG(197): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-17 02:17:39.561: A/DEBUG(197): Build fingerprint: 'google/hammerhead/hammerhead:6.0.1/MOB30M/2862625:user/release-keys'
05-17 02:17:39.561: A/DEBUG(197): Revision: '11'
05-17 02:17:39.561: A/DEBUG(197): ABI: 'arm'
05-17 02:17:39.561: A/DEBUG(197): pid: 21736, tid: 21736, name: hound-e.so  >>> /data/user/0/cc.gnaixx.hdog/cache/armeabi-v7a/hound-e.so <<<
05-17 02:17:39.561: A/DEBUG(197): signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0xb6fc31dc
05-17 02:17:39.562: W/NativeCrashListener(4484): Couldn't find ProcessRecord for pid 21736
05-17 02:17:39.552: W/debuggerd(197): type=1400 audit(0.0:4897): avc: denied { search } for name="cc.gnaixx.hdog" dev="mmcblk0p28" ino=1499822 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
05-17 02:17:39.562: A/DEBUG(197):     r0 00000026  r1 00000000  r2 00004001  r3 00000001
05-17 02:17:39.562: E/DEBUG(197): AM write failed: Broken pipe
05-17 02:17:39.563: A/DEBUG(197):     r4 00003612  r5 be939840  r6 5730636a  r7 be9397e8
05-17 02:17:39.563: A/DEBUG(197):     r8 00000000  r9 00000000  sl 00000000  fp be939a7c
05-17 02:17:39.563: A/DEBUG(197):     ip 000054e8  sp be938d50  lr b6fc31db  pc b6fc31dc  cpsr 400f0030
05-17 02:17:39.562: W/debuggerd(197): type=1400 audit(0.0:4898): avc: denied { search } for name="cc.gnaixx.hdog" dev="mmcblk0p28" ino=1499822 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
05-17 02:17:39.567: A/DEBUG(197): backtrace:
05-17 02:17:39.567: A/DEBUG(197):     #00 pc 000011dc  /data/data/cc.gnaixx.hdog/cache/armeabi-v7a/hound-e.so
05-17 02:17:39.567: A/DEBUG(197):     #01 pc 000017f1  /data/data/cc.gnaixx.hdog/cache/armeabi-v7a/hound-e.so
05-17 02:17:39.567: A/DEBUG(197):     #02 pc 00017359  /system/lib/libc.so (__libc_init+44)
05-17 02:17:39.567: A/DEBUG(197):     #03 pc 00000ba8  /data/data/cc.gnaixx.hdog/cache/armeabi-v7a/hound-e.so
05-17 02:17:39.562: W/debuggerd(197): type=1400 audit(0.0:4899): avc: denied { search } for name="cc.gnaixx.hdog" dev="mmcblk0p28" ino=1499822 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
05-17 02:17:39.590: A/DEBUG(197): Tombstone written to: /data/tombstones/tombstone_03
05-17 02:17:39.590: I/BootReceiver(4484): Copying /data/tombstones/tombstone_03 to DropBox (SYSTEM_TOMBSTONE)
`

**Comment by gnaixx** [comment]
这个只能脱很早版本的加固，可以忽略了
